version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test_nn_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r nn_model/requirements.txt
            py.test -vv nn_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_nn_model